/* M0 code generator: a deliberately tiny vertical slice.
 *
 * Handles `puts <expr>`, integer literals, and the +, -, * operators on
 * integers, emitting the same prologue and sp_* runtime calls the legacy
 * generator emits. This is the scaffold the later milestones grow into;
 * unhandled constructs abort with a clear "unsupported" message so gaps
 * are loud, not silent miscompiles.
 */
#include "codegen.h"
#include "node_table.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* ---- output buffer ---- */

typedef struct { char *p; size_t len, cap; } Buf;

static void buf_init(Buf *b) { b->p = NULL; b->len = 0; b->cap = 0; }

static void buf_putn(Buf *b, const char *s, size_t n) {
  if (b->len + n + 1 > b->cap) {
    size_t nc = b->cap ? b->cap * 2 : 256;
    while (nc < b->len + n + 1) nc *= 2;
    b->p = realloc(b->p, nc);
    b->cap = nc;
  }
  memcpy(b->p + b->len, s, n);
  b->len += n;
  b->p[b->len] = '\0';
}

static void buf_puts(Buf *b, const char *s) { buf_putn(b, s, strlen(s)); }

static void buf_printf(Buf *b, const char *fmt, ...) {
  char tmp[512];
  va_list ap;
  va_start(ap, fmt);
  int n = vsnprintf(tmp, sizeof(tmp), fmt, ap);
  va_end(ap);
  if (n < 0) return;
  if ((size_t)n < sizeof(tmp)) {
    buf_putn(b, tmp, (size_t)n);
  } else {
    char *big = malloc((size_t)n + 1);
    va_start(ap, fmt);
    vsnprintf(big, (size_t)n + 1, fmt, ap);
    va_end(ap);
    buf_putn(b, big, (size_t)n);
    free(big);
  }
}

/* ---- diagnostics ---- */

static void unsupported(const NodeTable *nt, int id, const char *what) {
  const char *ty = nt_type(nt, id);
  fprintf(stderr, "spinelc: unsupported %s: node %d (%s)\n",
          what, id, ty ? ty : "?");
  exit(1);
}

/* ---- expression emission ----
 * Appends the C text for node `id` to `b`. M0 types everything as int. */

static int is_op(const char *name, const char *op) {
  return name && strcmp(name, op) == 0;
}

static void emit_expr(const NodeTable *nt, int id, Buf *b) {
  const char *ty = nt_type(nt, id);
  if (!ty) unsupported(nt, id, "expression (no type)");

  if (strcmp(ty, "IntegerNode") == 0) {
    long long v = nt_int(nt, id, "value", 0);
    buf_printf(b, "%lldLL", v);
    return;
  }

  if (strcmp(ty, "CallNode") == 0) {
    const char *name = nt_str(nt, id, "name");
    int recv = nt_ref(nt, id, "receiver");
    int args = nt_ref(nt, id, "arguments");
    int argc = 0;
    const int *argv = NULL;
    if (args >= 0) argv = nt_arr(nt, args, "arguments", &argc);

    /* Binary integer operators: recv OP arg0 */
    if (recv >= 0 && argc == 1 &&
        (is_op(name, "+") || is_op(name, "-") || is_op(name, "*"))) {
      const char *fn = is_op(name, "+") ? "sp_int_add"
                     : is_op(name, "-") ? "sp_int_sub" : "sp_int_mul";
      buf_printf(b, "%s(", fn);
      emit_expr(nt, recv, b);
      buf_puts(b, ", ");
      emit_expr(nt, argv[0], b);
      buf_puts(b, ")");
      return;
    }

    unsupported(nt, id, "call");
  }

  unsupported(nt, id, "expression");
}

/* ---- statement emission ---- */

static void emit_stmt(const NodeTable *nt, int id, Buf *b) {
  const char *ty = nt_type(nt, id);
  if (!ty) unsupported(nt, id, "statement (no type)");

  if (strcmp(ty, "CallNode") == 0) {
    const char *name = nt_str(nt, id, "name");
    int recv = nt_ref(nt, id, "receiver");
    int args = nt_ref(nt, id, "arguments");
    int argc = 0;
    const int *argv = NULL;
    if (args >= 0) argv = nt_arr(nt, args, "arguments", &argc);

    if (is_op(name, "puts") && recv < 0 && argc == 1) {
      buf_puts(b, "    printf(\"%lld\\n\", (long long)");
      emit_expr(nt, argv[0], b);
      buf_puts(b, ");\n");
      return;
    }
  }

  /* Fall through: treat as a bare expression statement (no value used). */
  buf_puts(b, "    ");
  emit_expr(nt, id, b);
  buf_puts(b, ";\n");
}

/* ---- top-level driver ---- */

char *codegen_program(const NodeTable *nt) {
  Buf b;
  buf_init(&b);

  buf_puts(&b, "/* Generated by Spinel AOT compiler */\n");
  buf_puts(&b, "#include \"sp_runtime.h\"\n");
  buf_puts(&b, "static const char *sp_sym_to_s(sp_sym id){(void)id;return \"\";}\n\n");
  buf_puts(&b, "static const char *sp_class_to_s(sp_Class c){(void)c;return \"\";}\n\n\n");
  buf_puts(&b, "int main(int argc,char**argv){\n");
  buf_puts(&b, "    SP_GC_SAVE();\n\n");

  int root = nt->root_id;
  const char *rty = nt_type(nt, root);
  if (!rty || strcmp(rty, "ProgramNode") != 0) unsupported(nt, root, "root (expected ProgramNode)");
  int stmts = nt_ref(nt, root, "statements");
  if (stmts >= 0) {
    int n = 0;
    const int *body = nt_arr(nt, stmts, "body", &n);
    for (int k = 0; k < n; k++) emit_stmt(nt, body[k], &b);
  }

  buf_puts(&b, "  return 0;\n}\n");
  return b.p;
}
